In [1]:
import pandas as pd
import sklearn 
import numpy as np 
import matplotlib.pyplot as plt 
import statsmodels.api as sm
import seaborn as sns
sns.set()

# Add the Data from CSV file  (This is for SM)

In [3]:
data = pd.read_csv('1.02. Multiple linear regression.csv')
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [5]:
y = data['GPA']
x1 = data[['SAT','Rand 1,2,3']]


# Fit the OLS model 

In [14]:
x = sm.add_constant(x1)
result = sm.OLS(y,x).fit()


In [15]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    GPA   R-squared:                       0.407
Model:                            OLS   Adj. R-squared:                  0.392
Method:                 Least Squares   F-statistic:                     27.76
Date:                Tue, 27 Jul 2021   Prob (F-statistic):           6.58e-10
Time:                        10:49:29   Log-Likelihood:                 12.720
No. Observations:                  84   AIC:                            -19.44
Df Residuals:                      81   BIC:                            -12.15
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.2960      0.417      0.710      0.480      -0.533       1.125
SAT            0.0017      0.000      7.432      0.000       0.001       0.002
Rand 1,2,3    -0.0083      0.027     -0.304      0.762      -0.062       0.046
==============================================================================
Omnibus:                       12.992   Durbin-Watson:                   0.948
Prob(Omnibus):                  0.002   Jarque-Bera (JB):               16.364
Skew:                          -0.731   Prob(JB):                     0.000280
Kurtosis:                       4.594   Cond. No.                     3.33e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.33e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# Using Sklearn 

In [16]:
from sklearn.linear_model import LinearRegression

Import the Data 

In [17]:
data = pd.read_csv('1.02. Multiple linear regression.csv')
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [18]:
Dependent_want_to_predict = data['GPA']
Independent_predictor = data[['SAT','Rand 1,2,3']]

In [19]:
reg = LinearRegression()
reg.fit(Independent_predictor,Dependent_want_to_predict)

LinearRegression()

In [20]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [21]:
reg.intercept_

0.29603261264909486

Now we want to know the adjustment R insted of SCORE for R squared because here we're using more than one feature and if we have multiple features the adjustment R is more suitable for us


In [24]:
## r square 
reg.score(Independent_predictor,Dependent_want_to_predict )

0.40668119528142843

In [29]:
## Know the shape for x
Independent_predictor.shape


(84, 2)

In [32]:
## r adjustment
      ## n is for number of the obseravation
n = Independent_predictor.shape[0]
      ## p is number of predictor variables
p = Independent_predictor.shape[1]

      ## R 
rsquare = reg.score(Independent_predictor,Dependent_want_to_predict )
      ## R adjustments
radjustment = 1-(1-rsquare)*(n-1)/(n-p-1)
radjustment


0.39203134825134023

Feature selection

In [33]:
from sklearn.feature_selection import f_regression

In [36]:
p_value = f_regression(Independent_predictor,Dependent_want_to_predict)[1]
p_value

array([7.19951844e-11, 6.76291372e-01])

In [39]:
p_value.round(3)

array([0.   , 0.676])

Build summary table

In [42]:
reg_summary = pd.DataFrame(data = Independent_predictor.columns.values , columns=['Feature'])
reg_summary

Feature
0         SAT
1  Rand 1,2,3

In [43]:
reg_summary['Coffecient'] = reg.coef_
reg_summary['p values'] = p_value.round(3)

In [44]:
reg_summary

Feature  Coffecient  p values
0         SAT    0.001654     0.000
1  Rand 1,2,3   -0.008270     0.676

# Work with standraization 

In [47]:
data = pd.read_csv("1.02. Multiple linear regression.csv")
data

SAT  Rand 1,2,3   GPA
0   1714           1  2.40
1   1664           3  2.52
2   1760           3  2.54
3   1685           3  2.74
4   1693           2  2.83
..   ...         ...   ...
79  1936           3  3.71
80  1810           1  3.71
81  1987           3  3.73
82  1962           1  3.76
83  2050           2  3.81

[84 rows x 3 columns]

In [48]:
##dependent and independent variable 
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

Standraization 

In [50]:
from sklearn.preprocessing import StandardScaler

In [52]:
scaller = StandardScaler()

In [54]:
new_data = scaller.fit(x)
new_data

StandardScaler()

In [55]:
transform = scaller.transform(x)

In [56]:
transform

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

Linear regression with scalled data 

In [57]:
reg = LinearRegression()

In [58]:
##make the fit with the new scalled data 
Linear = reg.fit(transform,y)

In [60]:
Linear.coef_

array([ 0.17181389, -0.00703007])

In [61]:
Linear.intercept_

3.330238095238095

Build the summary Table

In [64]:
## build the summary table for rows and coulmns
reg_summary = pd.DataFrame([['Intercept'],['SAT'],['Rand 1,2,3']],columns=['Features'])
## add another column with name Weight and giive it the values 
reg_summary['Weight'] = reg.intercept_ ,reg.coef_[0] ,reg.coef_[1]

In [65]:
reg_summary

Features    Weight
0   Intercept  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [66]:
## The intercept is the B0 and B1 and B2 are the Coef_ for each variable

# Making prediction with scalled data 


In [74]:
new_data = pd.DataFrame(data=[[1700,2],[1800,1]], columns=['SAT' , 'Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [75]:
new_scalled_data = scaller.transform(new_data)
new_scalled_data

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [77]:
reg_sample = reg.predict(new_scalled_data)
reg_sample

array([3.09051403, 3.26413803])

In [84]:
new_data2 = pd.DataFrame(data=[[1700,2,reg.predict(new_scalled_data)[0]],[1800,1,reg.predict(new_scalled_data)[1]]], columns=['SAT' , 'Rand 1,2,3','Predictive'])

In [85]:
new_data2

SAT  Rand 1,2,3  Predictive
0  1700           2    3.090514
1  1800           1    3.264138